[project]
name = "wealthfolio_converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.67",
    "dotenv>=0.9.9",
    "duckdb>=1.5.4",
    "numpy>=2.5.1",
]

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "black>=26.5.1",
    "pylint[spelling]>=4.0.7",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.bandit]
skips = [
    # "B101",
]

[tool.bandit.assert_used]
skips = [
    "test_*.py",
]

[tool.pytest]
addopts = [
    "-v",
    "--cov=wealthfolio_converter",
    "--cov-report=html"
]
verbosity_subtests = "1"

[tool.pylint]
main.ignore-patterns = [ "^\\.#" , "test_.*\\.py" ]
"messages control".disable = [
  "bad-inline-option",
  "deprecated-pragma",
  "file-ignored",
  "locally-disabled",
  "raw-checker-failed",
  "suppressed-message",
  "use-implicit-booleaness-not-comparison-to-string",
  "use-implicit-booleaness-not-comparison-to-zero",
  "use-symbolic-message-instead",
  "useless-suppression",
  "logging-fstring-interpolation",
]